### ISSUE TITLE
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes

### ISSUE THREAD

**Issue by RahulGupta-Reflektion** [eleme/thrift_connector#27]
Thanks for writing down this great library. I am new to using thrift services. I can't seems to get it work. 

This is how I am querying thrift service with thrift_connector. This is throwing error that _Tsocket read 0 bytes._

```

import thriftpy
import thrift_connector.connection_pool as connection_pool
from tools.services.thriftservices import ExternalThriftServices
import json

request = <JSON_OBJECT>

pool = connection_pool.ClientPool(
        ExternalThriftServices,
        <HOST_NAME>,
        <PORT>,
        connction_class=connection_pool.ThriftClient
        )

pool.executeService(<SERVICE_NAME>, json.dumps(request))

```

However, I was able to extablish successful single connection with this code and receive the correct response.

```

import json
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from tools.services.thriftservices import ExternalThriftServices

request = <JSON_OBJECT>

socket = TSocket.TSocket(<HOST_NAME>,<PORT>)
transport = TTransport.TFramedTransport(socket)
transport.open()
protocol = TBinaryProtocol.TBinaryProtocol(transport)
thrift_client = ExternalThriftServices.Client(protocol)

thrift_client.executeService(<SERVICE_NAME>, json.dumps(request))

```

**Comment by wooparadog** [comment]
> from tools.services.thriftservices import ExternalThriftServices

you need to use the service loaded from thriftpy, not from the code generated by native thrift

**Comment by RahulGupta-Reflektion** [comment]
So, If I change earlier connection_pool usage to 

```
import thriftpy
import thrift_connector.connection_pool as connection_pool
from tools.services.thriftservices import ExternalThriftServices
import json

request = <JSON_OBJECT>
service = thriftpy.load("thriftService.thrift")

pool = connection_pool.ClientPool(
        service.ExternalThriftServices,
        <HOST_NAME>,
        <PORT>,
        connction_class=connection_pool.ThriftClient
        )

pool.executeService(<SERVICE_NAME>, json.dumps(request))
```

Then I get this error: 

AttributeError: type object 'ExternalThriftServices' has no attribute 'Client'

Is it because of mismatch between protocols or thriftpy versions?

**Comment by wooparadog** [comment]
We have a simple example for simple cases like this, please refer to the section (Usage) [https://github.com/eleme/thrift_connector#usage] in our readme.

**Comment by wooparadog** [comment]
Close old issues... 

If you find this problem still there, feel free to reopen.
