### ISSUE TITLE
[question] multiples ip

### ISSUE THREAD

**Issue by robsonpeixoto** [eleme/thrift_connector#31]
I have a very big thrift pool with more than 10 instancies in 10 different servers.
How can I use all theses IPs with `thrift_connector`?

**Comment by damnever** [comment]
You can use *MultiServerClient: https://github.com/eleme/thrift_connector/blob/master/thrift_connector/connection_pool.py#L544

Example(pseudo-code):
```Python
pools = [Pool(host=host, port=port) for (host, port) in server_ips]
multi_server = MultiServer(servers=pools)

pool = multi_server.yield_server()
with pool.connection_ctx() as client:
    client.ping()
```

**Comment by damnever** [comment]
You can use `*MultiServerClient(servers=server_ips)`: https://github.com/eleme/thrift_connector/blob/master/thrift_connector/connection_pool.py#L544-L562

**Comment by robsonpeixoto** [comment]
Thanks =D
